name: ml_linalg
description: SIMD-based linear algebra and statistics for data science
version: 12.11.0
homepage: https://github.com/gyrdym/ml_linalg

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  injector: ^1.0.8
  quiver: '>=2.0.0 <3.0.0'
  xrange: 0.0.8

dev_dependencies:
  benchmark_harness: '>=1.0.0 <2.0.0'
  build_runner: ^1.1.2
  build_test: ^0.10.2
  dartdoc: any
  grinder: ^0.8.3
  ml_tech: ^0.0.5
  mockito: ^3.0.0
  test: ^1.2.0
