name: ml_linalg
description: SIMD-based linear algebra and statistics for data science
version: 12.17.6
homepage: https://github.com/gyrdym/ml_linalg

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  injector: ^1.0.9
  quiver: '>=2.0.0 <3.0.0'
  xrange: ^0.0.9

dev_dependencies:
  benchmark_harness: '>=1.0.0 <2.0.0'
  build_runner: ^1.10.11
  build_test: ^1.3.2
  mockito: ^3.0.0
  pedantic: ^1.9.2
  test: ^1.15.7
  test_coverage: ^0.5.0
