name: ml_linalg
description: SIMD-based linear algebra and statistics for data science
version: 13.0.0
homepage: https://github.com/gyrdym/ml_linalg

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  quiver: ^3.0.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  build_runner: ^1.10.11
  build_test: ^1.3.2
  mockito: ^5.0.0-nullsafety.5
  pedantic: ^1.11.0
  test: ^1.16.0-nullsafety.17
  test_coverage: ^0.5.0
